services:
  backend:
    container_name: backend
    build:
      context: .
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - 3000:3000
    env_file:
      - .env
    networks:
      - api
    depends_on:
      - postgres

  postgres:
    image: postgres:latest
    container_name: ${DB_CONTAINER_NAME}
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - 5430:5432
    networks:
      - api
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    restart: unless-stopped

networks:
  api:

volumes:
  pgdata:
